name: learning_spanish
description: "A new Flutter project."
# publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  audioplayers: ^6.1.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_awesome_bottom_sheet: ^0.0.2
  flutter_bloc: ^8.1.5
  flutter_stepindicator: ^0.1.7
  flutter_tts: ^4.0.2
  fluttertoast: ^8.1.0
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  modal_bottom_sheet: ^3.0.0
  molten_navigationbar_flutter: ^1.0.1
  page_transition: ^2.1.0
  remove_diacritic: ^0.9.0
  rive_animated_icon: ^1.1.2
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.3
  subtitle_wrapper_package: ^2.2.1
  translator: ^1.0.0
  vibration: ^1.9.0
  youtube_explode_dart: ^2.2.1
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
    - assets/sounds/correctAnswer.mp3
    - assets/sounds/wrongAnswer.mp3
    - assets/sounds/hintSound.mp3
    - assets/lyrics/
    - assets/songs/
    - assets/lyrics/Heartstrings and Goodbyes.srt
    - assets/lyrics/Heartstrings and Goodbyes - Arabic.srt
    - assets/lyrics/1-Intro MAIN.srt
    